ALTER TABLE RECRUITMENT_APPLICATION
    ADD COLUMN IF NOT EXISTS portfolioUrl VARCHAR(500) NULL;

CREATE TABLE IF NOT EXISTS APPLICATION_APPLY_FIELD (
    applyFieldId INT AUTO_INCREMENT PRIMARY KEY,
    applicationId INT NOT NULL,
    applyField VARCHAR(50) NOT NULL,
    CONSTRAINT FK_APPLICATION_APPLY_FIELD_APPLICATION
        FOREIGN KEY (applicationId) REFERENCES RECRUITMENT_APPLICATION(applicationId) ON DELETE CASCADE,
    CONSTRAINT UQ_APPLICATION_APPLY_FIELD UNIQUE (applicationId, applyField)
);
