spring:
  application:
    name: nsu
  config:
    import: optional:file:.env[.properties]
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect

cloud:
  r2:
    endpoint: ${R2_ENDPOINT}
    access-key: ${R2_ACCESS_KEY}
    secret-key: ${R2_SECRET_KEY}
    bucket-name: ${R2_BUCKET_NAME}
    public-url: ${R2_PUBLIC_URL}
