name: Deploy to Server

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: 코드 Pull
        run: |
          cd /home/reverse/REVERSE-back
          git pull origin main

      - name: 빌드
        run: |
          cd /home/reverse/REVERSE-back
          ./gradlew bootJar

      - name: 서버 재시작
        run: |
          sudo systemctl restart nsu.service
          sudo systemctl status nsu.service