name: Deploy to Server

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: self-hosted
    defaults:
      run:
        working-directory: /home/reverse/REVERSE-back
    steps:
      - name: 코드 Pull
        run: |
          git pull origin main

      - name: 빌드
        run: |
          chmod +x gradlew
          ./gradlew bootJar

      - name: 서버 재시작
        run: |
          sudo systemctl restart nsu.service
          sudo systemctl status nsu.service --no-pager
